import React from 'react';

export const AvatarOptions = {
    topType: [
        { value: 'NoHair', label: 'Sem cabelo' },
        { value: 'Eyepatch', label: 'Tapa-olho' },
        { value: 'Hat', label: 'Chapéu' },
        { value: 'Hijab', label: 'Hijab' },
        { value: 'Turban', label: 'Turbante' },
        { value: 'WinterHat1', label: 'Chapéu de inverno 1' },
        { value: 'WinterHat2', label: 'Chapéu de inverno 2' },
        { value: 'WinterHat3', label: 'Chapéu de inverno 3' },
        { value: 'WinterHat4', label: 'Chapéu de inverno 4' },
        { value: 'LongHairBigHair', label: 'Cabelo longo - Cabelo grande' },
        { value: 'LongHairBob', label: 'Cabelo longo - Bob' },
        { value: 'LongHairBun', label: 'Cabelo longo - Coque' },
        { value: 'LongHairCurly', label: 'Cabelo longo - Cacheado' },
        { value: 'LongHairCurvy', label: 'Cabelo longo - Ondulado' },
        { value: 'LongHairDreads', label: 'Cabelo longo - Dreads' },
        { value: 'LongHairFrida', label: 'Cabelo longo - Frida' },
        { value: 'LongHairFro', label: 'Cabelo longo - Afro' },
        { value: 'LongHairFroBand', label: 'Cabelo longo - Afro com faixa' },
        { value: 'LongHairNotTooLong', label: 'Cabelo longo - Não muito longo' },
        { value: 'LongHairShavedSides', label: 'Cabelo longo - Laterais raspadas' },
        { value: 'LongHairMiaWallace', label: 'Cabelo longo - Mia Wallace' },
        { value: 'LongHairStraight', label: 'Cabelo longo - Liso' },
        { value: 'LongHairStraight2', label: 'Cabelo longo - Liso 2' },
        { value: 'LongHairStraightStrand', label: 'Cabelo longo - Mechas lisas' },
        { value: 'ShortHairDreads01', label: 'Cabelo curto - Dreads 1' },
        { value: 'ShortHairDreads02', label: 'Cabelo curto - Dreads 2' },
    ],
    accessoriesType: [
        { value: 'Blank', label: 'Nenhum' },
        { value: 'Kurt', label: 'Kurt' },
        { value: 'Prescription01', label: 'Óculos de receituário 1' },
        { value: 'Prescription02', label: 'Óculos de receituário 2' },
        { value: 'Round', label: 'Óculos redondos' },
        { value: 'Sunglasses', label: 'Óculos de sol' },
        { value: 'Wayfarers', label: 'Óculos wayfarers' },
    ],
    hatColor: [
        { value: 'Black', label: 'Preto' },
        { value: 'Blue01', label: 'Azul 01' },
        { value: 'Blue02', label: 'Azul 02' },
        { value: 'Blue03', label: 'Azul 03' },
        { value: 'Gray01', label: 'Cinza 01' },
        { value: 'Gray02', label: 'Cinza 02' },
        { value: 'Heather', label: 'Mescla' },
        { value: 'PastelBlue', label: 'Azul pastel' },
        { value: 'PastelGreen', label: 'Verde pastel' },
        { value: 'PastelOrange', label: 'Laranja pastel' },
        { value: 'PastelRed', label: 'Vermelho pastel' },
        { value: 'PastelYellow', label: 'Amarelo pastel' },
        { value: 'Pink', label: 'Rosa' },
        { value: 'Red', label: 'Vermelho' },
        { value: 'White', label: 'Branco' },
    ],
    hairColor: [
        { value: 'Auburn', label: 'Castanho-avermelhado' },
        { value: 'Black', label: 'Preto' },
        { value: 'Blonde', label: 'Loiro' },
        { value: 'BlondeGolden', label: 'Loiro dourado' },
        { value: 'Brown', label: 'Castanho' },
        { value: 'BrownDark', label: 'Castanho escuro' },
        { value: 'PastelPink', label: 'Rosa pastel' },
        { value: 'Platinum', label: 'Platina' },
        { value: 'Red', label: 'Vermelho' },
        { value: 'SilverGray', label: 'Cinza prateado' },
    ],
    facialHairType: [
        { value: 'Blank', label: 'Nenhum' },
        { value: 'BeardMedium', label: 'Barba média' },
        { value: 'BeardLight', label: 'Barba clara' },
        { value: 'BeardMajestic', label: 'Barba majestosa' },
        { value: 'MoustacheFancy', label: 'Bigode estiloso' },
        { value: 'MoustacheMagnum', label: 'Bigode magnum' },
    ],
    facialHairColor: [
        { value: 'Auburn', label: 'Castanho-avermelhado' },
        { value: 'Black', label: 'Preto' },
        { value: 'Blonde', label: 'Loiro' },
        { value: 'BlondeGolden', label: 'Loiro dourado' },
        { value: 'Brown', label: 'Castanho' },
        { value: 'BrownDark', label: 'Castanho escuro' },
        { value: 'Platinum', label: 'Platina' },
        { value: 'Red', label: 'Vermelho' },
    ],
    clotheType: [
        { value: 'BlazerShirt', label: 'Blazer com camisa' },
        { value: 'BlazerSweater', label: 'Blazer com suéter' },
        { value: 'CollarSweater', label: 'Gola com suéter' },
        { value: 'GraphicShirt', label: 'Camiseta com estampa' },
        { value: 'Hoodie', label: 'Moletom' },
        { value: 'Overall', label: 'Macacão' },
        { value: 'ShirtCrewNeck', label: 'Camiseta com gola redonda' },
        { value: 'ShirtScoopNeck', label: 'Camiseta com decote em U' },
        { value: 'ShirtVNeck', label: 'Camiseta com decote em V' },
    ],
    clotheColor: [
        { value: 'Black', label: 'Preto' },
        { value: 'Blue01', label: 'Azul 01' },
        { value: 'Blue02', label: 'Azul 02' },
        { value: 'Blue03', label: 'Azul 03' },
        { value: 'Gray01', label: 'Cinza 01' },
        { value: 'Gray02', label: 'Cinza 02' },
        { value: 'Heather', label: 'Mescla' },
        { value: 'PastelBlue', label: 'Azul pastel' },
        { value: 'PastelGreen', label: 'Verde pastel' },
        { value: 'PastelOrange', label: 'Laranja pastel' },
        { value: 'PastelRed', label: 'Vermelho pastel' },
        { value: 'PastelYellow', label: 'Amarelo pastel' },
        { value: 'Pink', label: 'Rosa' },
        { value: 'Red', label: 'Vermelho' },
        { value: 'White', label: 'Branco' },
    ],
    graphicType: [
        { value: 'Bat', label: 'Morcego' },
        { value: 'Cumbia', label: 'Cumbia' },
        { value: 'Deer', label: 'Veado' },
        { value: 'Diamond', label: 'Diamante' },
        { value: 'Hola', label: 'Hola' },
        { value: 'Pizza', label: 'Pizza' },
        { value: 'Resist', label: 'Resist' },
        { value: 'Selena', label: 'Selena' },
        { value: 'Bear', label: 'Urso' },
        { value: 'SkullOutline', label: 'Crânio contornado' },
        { value: 'Skull', label: 'Crânio' },
    ],
    eyeType: [
        { value: 'Close', label: 'Fechados' },
        { value: 'Cry', label: 'Chorando' },
        { value: 'Default', label: 'Padrão' },
        { value: 'Dizzy', label: 'Tonto' },
        { value: 'EyeRoll', label: 'Olhos revirados' },
        { value: 'Happy', label: 'Feliz' },
        { value: 'Hearts', label: 'Corações' },
        { value: 'Side', label: 'Olhos para o lado' },
        { value: 'Squint', label: 'Semicerro' },
        { value: 'Surprised', label: 'Surpreso' },
        { value: 'Wink', label: 'Piscando' },
        { value: 'WinkWacky', label: 'Piscando - Excêntrico' },
    ],
    eyebrowType: [
        { value: 'Angry', label: 'Bravo' },
        { value: 'AngryNatural', label: 'Bravo - Natural' },
        { value: 'Default', label: 'Padrão' },
        { value: 'DefaultNatural', label: 'Padrão - Natural' },
        { value: 'FlatNatural', label: 'Retas - Natural' },
        { value: 'RaisedExcited', label: 'Elevadas - Empolgado' },
        { value: 'RaisedExcitedNatural', label: 'Elevadas - Empolgado Natural' },
        { value: 'SadConcerned', label: 'Triste - Preocupado' },
        { value: 'SadConcernedNatural', label: 'Triste - Preocupado Natural' },
        { value: 'UnibrowNatural', label: 'Monocelha - Natural' },
        { value: 'UpDown', label: 'Arqueadas' },
        { value: 'UpDownNatural', label: 'Arqueadas - Natural' },
    ],
    mouthType: [
        { value: 'Concerned', label: 'Preocupado' },
        { value: 'Default', label: 'Padrão' },
        { value: 'Disbelief', label: 'Descrença' },
        { value: 'Eating', label: 'Comendo' },
        { value: 'Grimace', label: 'Careta' },
        { value: 'Sad', label: 'Triste' },
        { value: 'ScreamOpen', label: 'Grito - Boca aberta' },
        { value: 'Serious', label: 'Sério' },
        { value: 'Smile', label: 'Sorriso' },
        { value: 'Tongue', label: 'Língua para fora' },
        { value: 'Twinkle', label: 'Brilho' },
        { value: 'Vomit', label: 'Vômito' },
    ],
    skinColor: [
        { value: 'Tanned', label: 'Bronzeado' },
        { value: 'Yellow', label: 'Amarelo' },
        { value: 'Pale', label: 'Pálido' },
        { value: 'Light', label: 'Claro' },
        { value: 'Brown', label: 'Moreno' },
        { value: 'DarkBrown', label: 'Moreno escuro' },
        { value: 'Black', label: 'Negro' },
    ],
};
